name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Build Angular app
        run: npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          base_branch: main
          branch: stage
          folder: pmis_frontend/dist