name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install --force
          npm run build:prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
          branch: stage
          folder: pmis_frontend/dist