# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build  
      - working-directory: ./pmis_frontend
      - run: npm install --force && npm run build:prod && cp dist/index.html dist/404.html

      - name: Deploy
      - uses: JamesIves/github-pages-deploy-action@releases/v2
        with:
          base_branch: main
          branch: stage
          folder: pmis_frontend/dist
